### ISSUE TITLE
Figure out where indicator belongs

### ISSUE THREAD

**Issue by its02003** [OpenSLO/OpenSLO#29] opened 2021-06-10 19:20 UTC
Right now there seems to be a bit of an identity crisis between ratio based metrics and threshold metrics. To drive more consistency in where each thing is defined, move the data in the spec around

**Current ```thresholdMetric``` Implementation**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  indicator:
    thresholdMetric:
      source: '<source>'
      query: '<query_1>'
      queryType: '<query_type>'
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
      op: <op>
      value: <value>
      target: <target>
```

**Current ```ratioMetric``` Implementation**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  indicator:
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
       value: <value>
       target: <target>
       ratioMetric:
         incremental: <boolean>
         good:
           source: <source>
           queryType: <query>
           query: <query_string>
         total: # the denominator
           source: <source>
           queryType: <query>
           query: <query_string>
```

It would seem easier to manage the spec if the concept of the indicator was either universally handled outside of the objective or inside the objective, not split between them based on the metric type

Having this consistency would drive more universal consistency in SLO definitions.

Choices for implementation might look something like:

(a) **```ratioMetric``` as ```indicator```**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  indicator:
    ratioMetric:
       incremental: <boolean>
       good:
         source: <source>
         queryType: <query>
         query: <query_string>
       total: # the denominator
         source: <source>
         queryType: <query>
         query: <query_string>
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
       value: <value>
       target: <target>
```

**<OR>**

(b) **```indicator``` inside ```objective```**
```yaml
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: '<slo_1>'
spec:
  description: '<slo_1_description>'
  service: <service_a>
  timeWindows:
    - unit: <unit>
      count: <numeric>
      isRolling: <boolean>
  budgetingMethod: <method>
  objectives:
    - displayName: <display_name>
      op: <op>
      value: <value>
      target: <target>
      thresholdMetric:
        source: '<source>'
        query: '<query_1>'
        queryType: '<query_type>'
```

For the record, my vote is option (a) as this properly separates SLI from SLO in the spec

**Comment by its02003** [comment] 2021-06-16 17:09
@ian-bartholomew Is there a chance this is included in the undocumented decisions that https://github.com/OpenSLO/OpenSLO/issues/27 is intended to address?

**Comment by soasme** [comment] 2021-12-15 21:55
Just my two cents:

* Added a separate SLI data kind, which includes both thresholdMetric and ratioMetric. SLO.objectives[].ratioMetric & SLO.indicator.thresholdMetric are not needed as they're quite confusing to people.
* An SLO can have an embedded SLI via `indicator` or point to a pre-defined SLI data object via `indicatorRef`.

Here is my full proposal: https://gist.github.com/soasme/ac7e9d9286793c2466d8c9de959489cb

**Comment by kenfinnigan** [comment] 2021-12-16 14:29
I like this separation a lot, and was what I was thinking for this as well in terms of a separate SLI kind

**Comment by programmer04** [comment] 2022-04-25 13:26
PR #103 has been merged, the issue is considered resolved. Thanks for your involvment @its02003!

**Closed by programmer04** 2022-04-25 13:26 UTC
Labels: bug, documentation, help wanted
